### ISSUE TITLE
Is it possible to modify the monitored interfaces？

### ISSUE THREAD

**Issue by lee911214** [edirpedro/vnstat-dashboard#2]
Hi, I would like to ask about multiple interfaces, for example, after installing docker it will show docker0 interfaces, while the real one is not this one, and vnstat stats are not docker0. How to modify this case so that the interface only shows the name of the network card that vnstat stats are for? For example, my URL is http://45.83.107.238/vnstat

**Comment by edirpedro** [comment]
It reads all the interfaces that json output on the file. I found a small bug on that menu that will be fixed soon. To make it work just set alias to the interfaces you are using like `vnstat -i docker0 --setalias "Cable"`, set an alias for each interface that this make it work.

<img width="138" alt="Captura de Tela 2024-04-16 às 10 05 44" src="https://github.com/edirpedro/vnstat-dashboard/assets/831507/29254533-679a-4770-b96a-08041c289570">
