### ISSUE TITLE
Blank page when using Apache server

### ISSUE THREAD

**Issue by Aliens1de** [edirpedro/vnstat-dashboard#3]
Hi. Everything works great when i run php -S localhost:8000 inside /var/www/html/vnstat
But its a blank page with Apache/2.4.38. 
Getting these errors:
GET http://localhost/static/css/main.96310541.css net::ERR_ABORTED 404 (Not Found)
GET http://localhost/static/js/main.c4cfa62a.js net::ERR_ABORTED 404 (Not Found)
GET http://localhost/manifest.json 404 (Not Found)
Manifest: Line: 1, column: 1, Syntax error.

Any solutions?

**Comment by edirpedro** [comment]
You are running into a relative path and the app was built to use absolute path only. You have to place the files into `/var/www/html`, the root folder. Another solution is to create a [Virtual Host](https://httpd.apache.org/docs/2.4/mod/core.html#virtualhost) with a domain to point to that folder, to use like `http://vnstat.local`.

**Comment by Aliens1de** [comment]
It works with virtual host config! Thank you!
