### ISSUE TITLE
Wish to add mobile interface adaptation

### ISSUE THREAD

**Issue by lee911214** [edirpedro/vnstat-dashboard#5]
Hello. I've noticed that my configured web pages don't display well on my cell phone, it's messy. Is it possible to subsequently add a phone interface adaptation?
![a5b21303942ebd4bbe637e7358f1498](https://github.com/edirpedro/vnstat-dashboard/assets/93749545/dbb4dddd-54ef-4154-b1b2-c1ff43071a28)

**Comment by edirpedro** [comment]
Hi, the app was designed to be used on the desktop only, in a big screen. But as it's easy to provide access through the network to this interface for smartphones, I'll mark as a future implementation and see what can i reorganize for better reading.

**Comment by lee911214** [comment]
Thanks, looking forward to the new adaptations sson
